myproject/authapp/urls.py
import authapp.views as authapp
from django.urls import path, include

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
]

myproject/basketapp/urls.py
import basketapp.views as basketapp
from django.urls import path, include

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
    path('add/<int:products_id>/', basketapp.add, name='add'),
    path('remove/<int:products_basket_id>/', basketapp.remove, name='remove'),
]

myproject/myapp/urls.py
import myapp.views as myapp
from django.urls import path

app_name = 'myapp'

urlpatterns = [
    path('', myapp.index, name='index'),
    path('catalog/', myapp.catalog, name='catalog'),

    path('catalog/category/<int:category_pk>/', myapp.catalog_section, name='catalog_section'),

    path('catalog/product/<int:product_pk>/', myapp.product_page, name='product_page'),
]

myproject/myproject/urls.py
import myapp.views as myapp
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('myapp.urls', namespace='my')),
    path('auth/', include('authapp.urls', namespace='auth')),

    path('basket/', include('basketapp.urls', namespace='basket')),

    path('admin/', admin.site.urls),

]

myproject/basketapp/models.py
from django.contrib.auth.models import User
from django.db import models

from myapp.models import Products


class ProductsBasket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ForeignKey(Products, on_delete=models.CASCADE)
    added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.added.strftime("%Y.%m.%d %H:%M")}: {self.products.name}'

    def to_html(self):
        return f'{self.added.strftime("%Y.%m.%d %H:%M")}: <b>{self.products.name}</b>'

myproject/myapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField('Название', max_length=128)
    desc = models.TextField('Описание', blank=True)

    def __str__(self):
        return self.name


class Products(models.Model):
    category = models.ForeignKey(ProductCategory,
                                 on_delete=models.CASCADE)
    name = models.CharField('Название', max_length=200)
    desc = models.TextField('Описание', blank=True)

    # price = models.IntegerField('Цена', default=0)
    is_active = models.BooleanField('Активно', default=True)

    def __str__(self):
        return self.name

myproject/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',
                  'password1', 'password2', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'
            # item.help_text = ''

myproject/authapp/views.py
import django.contrib.auth as auth
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from authapp.forms import LoginForm, RegisterForm


def login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            auth.login(request, form.get_user())
            return HttpResponseRedirect(reverse('my:index'))
    else:
        form = LoginForm()

    context = {
        'page_title': 'авторизация',
        'form': form,
    }
    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('my:index'))


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        form = RegisterForm()

    context = {
        'page_title': 'регистрация',
        'form': form,
    }
    return render(request, 'authapp/register.html', context)

myproject/basketapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

from basketapp.models import ProductsBasket
from django.urls import reverse

from myapp.models import Products


def index(request):
    item = ProductsBasket.objects.filter(user=request.user)
    context = {
        'object_list': item,
    }
    return render(request, 'basketapp/basket.html', context)


def add(request, products_id):
    products = Products.objects.get(pk=products_id)
    ProductsBasket.objects.get_or_create(
       user=request.user,
       products=products
    )
    return HttpResponseRedirect(
       reverse('my:catalog_section',
               kwargs={'category_pk': products.category_id})
    )


def remove(request, products_basket_id):
    item = ProductsBasket.objects.get(id=products_basket_id)
    item.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

myproject/myapp/views.py
from django.shortcuts import render

from myapp.models import ProductCategory, Products


def index(request):
    context = {
        'page_title': 'главная'
    }
    return render(request, 'myapp/index.html', context)


def catalog(request):
    categories = ProductCategory.objects.all()
    context = {
        'categories': categories,
        'page_title': 'каталог'
    }
    return render(request, 'myapp/catalog.html', context)


def catalog_section(request, category_pk):
    items = Products.objects.filter(category_id=category_pk)
    context = {
        'items': items,
        'page_title': 'страница товаров'
    }
    return render(request, 'myapp/catalog_section.html', context)


def product_page(request, product_pk):
    product = Products.objects.get(pk=product_pk)
    context = {
        'product': product,
        'page_title': 'страница товара'
    }
    return render(request, 'myapp/product_page.html', context)

myproject/authapp/templates/authapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|default:'аутентификация'|capfirst }}</title>
    {% block css %}
        <link rel="stylesheet" href="/static/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/css/style.css">
    {% endblock %}
    {% block js %}
        <script src="/static/js/jquery-3.2.1.slim.min.js"></script>
        <script src="/static/js/bootstrap.min.js"></script>
    {% endblock %}
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

myproject/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}

{% block content %}
    <div class="login-form">
        <div class="form-title">Вход в систему</div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit"
                   class="btn btn-dark form-control"
                   value="Войти">
        </form>
        <br>
        <a class="btn btn-dark form-control" href="{% url 'auth:register' %}">
            Зарегистрироваться
        </a>
    </div>
{% endblock %}

myproject/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}

{% block content %}
    <div class="register-form">
        <div class="form-title">Регистрация</div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit"
                   class="btn btn-dark form-control"
                   value="Зарегистрироваться">
        </form>
    </div>
{% endblock %}

myproject/basketapp/templates/basketapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|default:"Главная"|capfirst }}</title>
    {% block css %}
        <link rel="stylesheet" href="/static/css/style.css">
        <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    {% endblock %}
    {% block js %}
        <script src="/static/js/jquery-3.2.1.slim.min.js"></script>
        <script src="/static/js/bootstrap.min.js"></script>
    {% endblock %}
</head>
<body>
{% block menu %}
<nav>
    <ul class="topmenu">
        <li>
            <a href="{% url 'my:index' %}">Главная</a>
        </li>
        <li>
            <a href="{% url 'my:catalog' %}" class="down">Каталог</a>
        </li>
        <li>
        <a href="{% url 'basket:index' %}">Корзина</a>
        </li>
        <li>
            {% if user.is_authenticated %}
                <a href="{% url 'auth:logout' %}">Выйти</a>
            {% else %}
                <a href="{% url 'auth:login' %}">Войти</a>
            {% endif %}
        </li>

    </ul>
</nav>
{% endblock %}
{% block content %}
{% endblock %}
</body>
</html>

myproject/basketapp/templates/basketapp/basket.html
{% extends 'basketapp/base.html' %}
{% block content %}
    <div class="basket">
        <h2>Корзина работает, {{user.username}}</h2>
        <ul>
            {% for item in object_list %}
                <li>
                    {{ item.to_html|safe}}
                    <a href="{% url 'basket:remove' item.pk %}" class="btn btn-danger">удалить</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

myproject/myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|default:"Главная"|capfirst }}</title>
    {% block css %}
        <link rel="stylesheet" href="/static/css/style.css">
        <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    {% endblock %}
    {% block js %}
        <script src="/static/js/jquery-3.2.1.slim.min.js"></script>
        <script src="/static/js/bootstrap.min.js"></script>
    {% endblock %}
</head>
<body>
{% block menu %}
<nav>
    <ul class="topmenu">
        <li><a href="{% url 'my:index' %}">Главная</a></li>
        <li><a href="{% url 'my:catalog' %}" class="down">Каталог</a>
        <li><a href="{% url 'basket' %}">Корзина</a></li>
        <li>
            {% if user.is_authenticated %}
                <a href="{% url 'auth:logout' %}">Выйти</a>
            {% else %}
                <a href="{% url 'auth:login' %}">Войти</a>
            {% endif %}
        </li>

    </ul>
</nav>
{% endblock %}
{% block content %}

{% endblock %}

</body>
</html>

myproject/myapp/templates/myapp/basket.html
{% extends 'myapp/base.html' %}

myproject/myapp/templates/myapp/catalog.html
{% extends 'myapp/base.html' %}

{% block content %}
    <h1>Каталог</h1>
    <div class="catalog-menu">
        <ul>
            {% for item in categories %}
                <li>
                    <h3><a href="{% url 'my:catalog_section' item.pk %}">
                        {{ item }}
                    </a></h3>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

myproject/myapp/templates/myapp/catalog_page.html
{% extends 'myapp/base.html' %}

{% block content %}
    <h1>Страница каталога</h1>
    <div class="catalog-menu">
        <ul>
            {% for item in items %}
                <li>
                    <h4><a href="{% url 'product_page' item.pk %}">
                        {{ item }}
                    </a></h4>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

myproject/myapp/templates/myapp/catalog_section.html
{% extends 'myapp/base.html' %}

{% block content %}
    <h1>Страница каталога</h1>
    <div class="catalog-menu">
        <ul>
            {% for item in items %}
                <li>
                    <h4><a href="{% url 'my:product_page' item.pk %}">
                        {{ item }}
                    </a></h4>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

myproject/myapp/templates/myapp/ccatalog.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Главная</title>
    {% block css %}
        <link rel="stylesheet" href="/static/css/catalog.css">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<nav>
    <ul class="topmenu">
        <li><a href="/">Главная</a></li>
        <li><a href="/catalog/" class="down">Каталог</a>
            <ul class="submenu">
                <li><a href="">Компьютерная техника</a></li>
                <li><a href="">Бытовая техника</a></li>
                <li><a href="">Мобильные телефоны</a></li>
            </ul>
        </li>
        <li><a href="/basket/">Корзина</a></li>
    </ul>
</nav>

<div class="catalog">
    <img src="\static\img\keyboard.jpg" alt="keyboard">
    <h2>
        <span>Периферия и аксессуары</span>
    </h2>

    <img src="\static\img\motherboard.jpg" alt="motherboard">
    <h2>Комплектующие</h2>

</div>
</body>
</html>

myproject/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block content %}
{#<form>#}
{#  <div class="container">#}
{#    <h1>Регистрация</h1>#}
{#    <p>Пожалуйста заполните эту форму для регистрации аккаунта.</p>#}
{#    <hr>#}
{##}
{#    <label for="email"><b>Ваш e-mail(он же будет логином)*</b></label>#}
{#    <input type="text" placeholder="Адрес вашей электронной почты" name="email" required>#}
{##}
{#    <label for="psw"><b>Пароль</b></label>#}
{#    <input type="password" placeholder="Задайте пароль" name="psw" required>#}
{##}
{#    <label for="psw-repeat"><b>Повторите пароль</b></label>#}
{#    <input type="password" placeholder="Повторите заданный пароль" name="psw-repeat" required>#}
{#    <hr>#}
{#    <p>Создавая учетную запись, вы соглашаетесь с нашими <a href="#">Условия и конфиденциальности</a>.</p>#}
{##}
{#    <button type="submit" class="registerbtn">Регистрация</button>#}
{#  </div>#}
{##}
{#  <div class="container signin">#}
{#    <p>Уже есть аккаунт? <a href="#">Войти в систему</a>.</p>#}
{#  </div>#}
{#</form>#}
{% endblock %}

myproject/myapp/templates/myapp/product_page.html
{% extends 'myapp/base.html' %}

{% block content %}
    <h1>Товар</h1>
    <p class="product-name">
    Название: {{ product.name }}
    <p class="product_desc">
        Описание: {{ product.desc }}
    </p>
    <a href="{% url 'basket:add' product.id %}"
       class="btn btn-dark">
        купить
    </a>

{% endblock %}